version: '3.8'

services:
  web_api:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - Redis__ConnectionString=redis-0:6379
    depends_on:
      - redis
    networks:
      - my_network
  
  worker_instance1:
    build:
      context: .
      dockerfile: Consumer.WebApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - Redis__ConnectionString=redis-0:6379
    depends_on:
      - redis
    networks:
      - my_network
  
  worker_instance2:
    build:
      context: .
      dockerfile: Consumer.WebApi/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - Redis__ConnectionString=redis-0:6379
    depends_on:
      - redis
    networks:
      - my_network
  
  redis:
    container_name: redis-0
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge